### ISSUE TITLE
feat: Orchestrator - Detect the container entrypoint issues (cannot find/launch container executable) and put the info in logs

### ISSUE THREAD

**Issue by Ark-kun** [Cloud-Pipelines/backend#3]
Currently this information is not relayed to the user.
```
phase: Failed
 containerStatuses:
  - containerID: containerd://519911abbe914ba4739a927ac5c5c62e26b6f8ffe93a4a28a86e70a47094ca98
    image: sha256:d173511e8fb6e428b89376cd8d86f6a7426fc0e4c4f068cabc0686b6a775e2fa
    imageID: us-central1-docker.pkg.dev/shopify-discovery-relevance/oasis-user-containers/tmp-pete-3@sha256:5cfdb19ee00fe158e4af6433d46409a47e0ae6b73a4d19b67e78f3cc3de33b00
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://519911abbe914ba4739a927ac5c5c62e26b6f8ffe93a4a28a86e70a47094ca98
        exitCode: 128
        finishedAt: "2025-05-05T15:29:28Z"
        message: 'failed to create containerd task: failed to create shim task: OCI
          runtime create failed: runc create failed: unable to start container process:
          exec: "sh - -c - | echo \"Processing query set\" ./process_queryset \"$0\"
          \"$1\" \"$2\"": stat sh - -c - | echo "Processing query set" ./process_queryset
          "$0" "$1" "$2": no such file or directory: unknown'
        reason: StartError
        startedAt: "1970-01-01T00:00:00Z"

```
