### ISSUE TITLE
feat: Orchestrator - Kubernetes - Detect the container image pulling issues and fail the container execution

### ISSUE THREAD

**Issue by Ark-kun** [Cloud-Pipelines/backend#4]
Currently, the container forever remains in Pending state (which can resolve itself if teh container image issues are resolved).
```
phase: Pending
 containerStatuses:
  - image: us-central1-docker.pkg.dev/.../tmp@sha256:223066d62adc4851543d0b1e5e9f89bf118cb56bf589745d711c2ccc64e67ac6
    imageID: ""
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "us-central1-docker.pkg.dev/.../tmp@sha256:223066d62adc4851543d0b1e5e9f89bf118cb56bf589745d711c2ccc64e67ac6"
        reason: ImagePullBackOff

```
